baseURL = "http://uprooted.unc.edu/"
defaultContentLanguage = "en"
copyright = ""
title = "Uprooted: Venezuelan Families Flee to Colombia"
themesDir = "../.."

[languages]
  [languages.en]
    title = "Uprooted: Venezuelan Families Flee to Colombia"
    weight = "1"
    [languages.en.params]
      
  [languages.es]
    title = ""
    weight = "2"
    [languages.es.params]
      
      [languages.es.params.navigation]
        help = "Ayuda"
      


[params]
  google_analytics_id = ""

  [params.homepage_meta_tags]
    meta_description = "Uprooted is a multimedia journalism project produced by the UNC School of Media and Journalism"
    meta_og_title = "Uprooted: Venezuelan Families Flee to Colombia"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@"
    meta_twitter_creator = "@"
  [params.navigation]
    help = "Help"

[permalinks]
  post = "/:year/:month/:day/:slug"
  pages = "/:filename"




