baseURL = "/"
defaultContentLanguage = "en"
copyright = ""
title = "Uprooted: Venezuelan Families Flee to Colombia"
themesDir = "../.."
enableInlineShortcodes = "true"
relativeURLs = "true"
canonifyURLs = "true"


[languages]
  [languages.en]
    title = "Uprooted: Venezuelan Families Flee to Colombia"
    weight = "1"
    languageName = "English"
    languageCode = "en"
    [languages.en.params]
      
  [languages.es]
    title = " "
    weight = "2"
    languageName = "Español"
    languageCode = "es"
    [languages.es.params]
      
      [languages.es.params.navigation]
        help = "Ayuda"
[[languages.es.menu.main]]
	name = "Spanish Story 1 Name"
	url = "/es/story1/"
  weight = 1

[[languages.es.menu.main]]
  name = "Wasted Skills Abound"
  url = "/es/story2/"
  weight = 2

[[languages.es.menu.main]]
  name = "Providing Necessary Aid"
  url = "/es/story3/"
  weight = 3

[[languages.es.menu.main]]
  name = "Generation in Limbo"
  url = "/es/story4/"
  weight = 4 

[[languages.es.menu.main]]
  name = "Road to Wellness"
  url = "/es/story5/"
  weight = 5

[params]
  google_analytics_id = ""
  gh_pages_URL = "https://brookenf.github.io/uprooted-mejo584/"

  [params.homepage_meta_tags]
    meta_description = "Uprooted is a multimedia journalism project produced by the UNC School of Media and Journalism"
    meta_og_title = "Uprooted: Venezuelan Families Flee to Colombia"
    meta_og_type = "website"
    meta_og_url = "https://uprooted.unc.edu"
    meta_og_image = ""
    meta_og_description = "Uprooted is a multimedia storytelling project of the UNC School of Media and Journalism. The stories focus on the adjustments of the lives of Venezuelan migrants to Medellin, Colombia."
    meta_twitter_card = "summary"
    meta_twitter_site = "@uprootedunc"
    meta_twitter_creator = "@uprootedunc"
  [params.navigation]
    help = "Help"


[menu]
  [[menu.main]]
    name = "Undocumented Venezuelans find their livelihood by singling on the street."
    url = "/finding-your-voice/"
    weight = 1
    pre = "<p class='story-topic'>Documentation</p><h3 class='story-title'>Finding Your Voice</h3>"
    post = "/images/gov-homepagestill.jpg"

  [[menu.main]]
    name = "Venezuelans find camaraderie, family and support through sport."
    url = "/making-it-work/"
    weight = 2
    pre = "<p class='story-topic'>Economy</p><h3 class='story-title'>Making It Work</h3>"
    post = "/images/econ-homepagestill.jpg"

  [[menu.main]]
    name = "A family’s sacrifice for their children’s health still has roadblocks."
    url = "/the-greatest-need/"
    weight = 3
    pre = "<p class='story-topic'>Health</p><h3 class='story-title'>The Greatest Need</h3>"
    post = "/images/health-homepagestill.jpg"

  [[menu.main]]
    name = "Children sacrifice their education to help their families."
    url = "/cost-of-dreams/"
    weight = 4 
    pre = "<p class='story-topic'>Education</p><h3 class='story-title'>The Cost of Dreams</h3>"
    post = "/images/education-homepagestill.jpg"

  [[menu.main]]
    name = "A mother’s effort to provide and reunite with her children."
    url = "/a-mothers-sacrifice/"
    weight = 5
    pre = "<p class='story-topic'>Women</p><h3 class='story-title'>A Mother's Sacrifice</h3>"
    post = "/images/women-homepagestill.jpg"

  [[menu.photo]]
    name = "This is the first chapter of the photo stories"
    url = "/what-they-carry/"
    weight = 1
    pre = "<p class='story-topic'>Chapter One</p><h3 class='story-title'>What They Carry</h3>"
    post = "/images/photo-chap-1-hero.jpg"

  [[menu.photo]]
    name = "This is the second chapter of the photo stories"
    url = "/a-new-home/"
    weight = 2
    pre = "<p class='story-topic'>Chapter Two</p><h3 class='story-title'>A New Home</h3>"
    post = "/images/photo-chap-2-hero.jpg"

  [[menu.photo]]
    name = "This is the third chapter of the photo stories"
    url = "/a-family-together/"
    weight = 3
    pre = "<p class='story-topic'>Chapter Three</p><h3 class='story-title'>A Family, Together</h3>"
    post = "/images/photo-chap-3-hero.jpg"

  [[menu.photo]]
    name = "This is the fourth chapter of the photo stories"
    url = "/making-it-in-medellin/"
    weight = 4
    pre = "<p class='story-topic'>Chapter Four</p><h3 class='story-title'>Making it in Medellín</h3>"
    post = "/images/photo-chap-4-hero.jpg"
 

[permalinks]
  post = "/:slug"
  pages = "/:filename"




