baseURL = ""
defaultContentLanguage = "en"
copyright = ""
title = "Uprooted: Venezuelan Families Flee to Colombia"
themesDir = "../.."
enableInlineShortcodes = "true"
relativeURLs = "true"
canonifyURLs = "true"


[languages]
  [languages.en]
    title = "Uprooted: Venezuelan Families Flee to Colombia"
    weight = "1"
    [languages.en.params]
      
  [languages.es]
    title = ""
    weight = "2"
    [languages.es.params]
      
      [languages.es.params.navigation]
        help = "Ayuda"
      


[params]
  google_analytics_id = ""
  gh_pages_URL = "https://brookenf.github.io/uprooted-mejo584/"

  [params.homepage_meta_tags]
    meta_description = "Uprooted is a multimedia journalism project produced by the UNC School of Media and Journalism"
    meta_og_title = "Uprooted: Venezuelan Families Flee to Colombia"
    meta_og_type = "website"
    meta_og_url = "https://uprooted.unc.edu"
    meta_og_image = ""
    meta_og_description = "Uprooted is a multimedia storytelling project of the UNC School of Media and Journalism. The stories focus on the adjustments of the lives of Venezuelan migrants to Medellin, Colombia."
    meta_twitter_card = "summary"
    meta_twitter_site = "@uprootedunc"
    meta_twitter_creator = "@uprootedunc"
  [params.navigation]
    help = "Help"

[[menu.main]]
	name = "A Helping Hand"
	url = "/story1/"
  weight = 1

[[menu.main]]
  name = "Wasted Skills Abound"
  url = "/story2/"
  weight = 2

[[menu.main]]
  name = "Providing Necessary Aid"
  url = "/story3/"
  weight = 3

[[menu.main]]
  name = "Generation in Limbo"
  url = "/story4/"
  weight = 4 

[[menu.main]]
  name = "Road to Wellness"
  url = "/story5/"
  weight = 5

[[menu.main]]
  name = "Embracing Medellín"
  url = "/interactive/"
  weight = 6

[permalinks]
  post = "/:slug"
  pages = "/:filename"




