baseURL = "http://uprooted.unc.edu/"
defaultContentLanguage = "en"
copyright = "Copyright School of Media and Journalism"
title = "Uprooted: Venezuelan Families Flee to Colombia"
themesDir = "../.."
enableInlineShortcodes = "true"
relativeURLs = "true"
canonifyURLs = "true"


[languages]
  [languages.en]
    title = "Uprooted: Venezuelan Families Flee to Colombia"
    weight = "1"
    languageName = "English"
    languageCode = "en"
    [languages.en.params]
      
  [languages.es]
    title = " "
    weight = "2"
    languageName = "Español"
    languageCode = "es"
    [languages.es.params]
      
      [languages.es.params.navigation]
        help = "Ayuda"
[[languages.es.menu.main]]
	url = "/es/a-hopeful-voice/"
  weight = 1
  name = "Undocumented Venezuelans find their livelihood by singling on the street."
  pre = "<p class='story-topic'>Documentación</p><h3 class='story-title'>A Hopeful Voice</h3>"
  post = "http://uprooted.unc.edu/images/gov-homepagestill.jpg"

[[languages.es.menu.main]]
  url = "/es/brothers-on-the-pitch/"
  weight = 2
  name = "The Soccer Story"
  pre = "<p class='story-topic'>Economía</p><h3 class='story-title'>Resolviendo</h3>"
  post = "http://uprooted.unc.edu/images/econ-homepagestill.jpg"

[[languages.es.menu.main]]
  url = "/es/greater-than-death/"
  weight = 3
  name = "The health story"
  pre = "<p class='story-topic'>Salud</p><h3 class='story-title'>Greater than Death</h3>"
  post = "http://uprooted.unc.edu/images/health-homepagestill.jpg"

[[languages.es.menu.main]]
  url = "/es/cost-of-dreams/"
  weight = 4 
  name = "The education story"
  pre = "<p class='story-topic'>Educación</p><h3 class='story-title'>Lo que Cuestan los Sueños</h3>"
  post = "http://uprooted.unc.edu/images/education-homepagestill.jpg"  

[[languages.es.menu.main]]
  url = "/es/a-mother-sacrifice/"
  weight = 5
  name = "The women story"
  pre = "<p class='story-topic'>Las Mujeres</p><h3 class='story-title'>El Sacrificio de una Madre</h3>"
  post = "http://uprooted.unc.edu/images/women-homepagestill.jpg"

# Menu in spanish for photo journey
[[languages.es.menu.photo]]
    name = "Venezuelans travel to Medellín clutching some things with a tighter grip."
    url = "/es/what-they-carry/"
    weight = 1
    pre = "<p class='story-topic'>Chapter One</p><h3 class='story-title'>What They Carry</h3>"
    post = "http://uprooted.unc.edu/images/photo-chap-1-hero.jpg"

[[languages.es.menu.photo]]
    name = "An inside look into where migrants live after leaving home."
    url = "/es/a-new-home/"
    weight = 2
    pre = "<p class='story-topic'>Chapter Two</p><h3 class='story-title'>A New Home</h3>"
    post = "http://uprooted.unc.edu/images/photo-chap-2-hero.jpg"

  [[languages.es.menu.photo]]
    name = "A family struggles to survive, having arrived in Medellin ten days prior."
    url = "/es/a-family-together/"
    weight = 3
    pre = "<p class='story-topic'>Chapter Three</p><h3 class='story-title'>A Family, Together</h3>"
    post = "http://uprooted.unc.edu/images/photo-chap-3-hero.jpg"

  [[languages.es.menu.photo]]
    name = "The success stories of Venezuelan immigrants in a new country."
    url = "/es/making-it-in-medellin/"
    weight = 4
    pre = "<p class='story-topic'>Chapter Four</p><h3 class='story-title'>Making it in Medellín</h3>"
    post = "http://uprooted.unc.edu/images/photo-chap-4-hero.jpg"

[params]
  google_analytics_id = ""
  gh_pages_URL = "https://brookenf.github.io/uprooted-mejo584/"

  [params.homepage_meta_tags]
    meta_description = "Uprooted is a multimedia journalism project produced by the UNC School of Media and Journalism"
    meta_og_title = "Uprooted: Venezuelan Families Flee to Colombia"
    meta_og_type = "website"
    meta_og_url = "http://uprooted.unc.edu"
    meta_og_image = "http://uprooted.unc.edu/images/home5.JPG"
    meta_og_description = "Uprooted is a multimedia storytelling project of the UNC School of Media and Journalism. The stories focus on the adjustments of the lives of Venezuelan migrants to Medellin, Colombia."
    meta_twitter_card = "Uprooted is a multimedia storytelling project of the UNC School of Media and Journalism. The stories focus on the adjustments of the lives of Venezuelan migrants to Medellin, Colombia."
    meta_twitter_site = "@uprootedunc"
    meta_twitter_creator = "@uprootedunc"
  [params.navigation]
    help = "Help"


[menu]
  [[menu.main]]
    name = "Undocumented Venezuelans find their livelihood by singling on the street."
    url = "/a-hopeful-voice/"
    weight = 1
    pre = "<p class='story-topic'>Documentation</p><h3 class='story-title'>A Hopeful Voice</h3>"
    post = "/images/gov-homepagestill.jpg"

  [[menu.main]]
    name = "Venezuelans find camaraderie, family and support through sport."
    url = "/brothers-on-the-pitch/"
    weight = 2
    pre = "<p class='story-topic'>Economy</p><h3 class='story-title'>Brothers on the Pitch</h3>"
    post = "/images/econ-homepagestill.jpg"

  [[menu.main]]
    name = "A family’s sacrifice for their children’s health still has roadblocks."
    url = "/greater-than-death/"
    weight = 3
    pre = "<p class='story-topic'>Health</p><h3 class='story-title'>Greater than Death</h3>"
    post = "/images/health-homepagestill.jpg"

  [[menu.main]]
    name = "Children sacrifice their education to help their families."
    url = "/cost-of-dreams/"
    weight = 4 
    pre = "<p class='story-topic'>Education</p><h3 class='story-title'>The Cost of Dreams</h3>"
    post = "/images/education-homepagestill.jpg"

  [[menu.main]]
    name = "A mother’s effort to provide and reunite with her children."
    url = "/a-mothers-sacrifice/"
    weight = 5
    pre = "<p class='story-topic'>Women</p><h3 class='story-title'>A Mother's Sacrifice</h3>"
    post = "/images/women-homepagestill.jpg"

  [[menu.photo]]
    name = "Venezuelans travel to Medellín clutching some things with a tighter grip."
    url = "/what-they-carry/"
    weight = 1
    pre = "<p class='story-topic'>Chapter One</p><h3 class='story-title'>What They Carry</h3>"
    post = "/images/photo-chap-1-hero.jpg"

  [[menu.photo]]
    name = "An inside look into where migrants live after leaving home."
    url = "/a-new-home/"
    weight = 2
    pre = "<p class='story-topic'>Chapter Two</p><h3 class='story-title'>A New Home</h3>"
    post = "/images/photo-chap-2-hero.jpg"

  [[menu.photo]]
    name = "A family struggles to survive, having arrived in Medellin ten days prior."
    url = "/a-family-together/"
    weight = 3
    pre = "<p class='story-topic'>Chapter Three</p><h3 class='story-title'>A Family, Together</h3>"
    post = "/images/photo-chap-3-hero.jpg"

  [[menu.photo]]
    name = "The success stories of Venezuelan immigrants in a new country."
    url = "/making-it-in-medellin/"
    weight = 4
    pre = "<p class='story-topic'>Chapter Four</p><h3 class='story-title'>Making it in Medellín</h3>"
    post = "/images/photo-chap-4-hero.jpg"
 

[permalinks]
  post = "/:slug"
  pages = "/:filename"




